apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - migrate-job.yaml
  - gateway.yaml
  - inventory.yaml
  - reservation.yaml
  - payment.yaml
  - reconciliation.yaml
  - notification.yaml
  - discovery.yaml
  - pricing.yaml
  - hpa.yaml
  - pdb.yaml
